name: veggo
services:
  postgres-veggo:
    image: postgres:16
    container_name: postgres-veggo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    ports:
      - "${DATABASE_HOST_PORT}:${DATABASE_CONT_PORT}"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - network-veggo

  minio-veggo:
    image: minio/minio:latest
    container_name: minio-veggo
    ports:
      - "${MINIO_HOST_PORT}:${MINIO_CONT_PORT}"
      - "${MINIO_DASH_HOST_PORT}:${MINIO_DASH_CONT_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: >
      server /data
      --address ":${MINIO_CONT_PORT}"
      --console-address ":${MINIO_DASH_CONT_PORT}"
    volumes:
      - minio_data:/data
    networks:
      - network-veggo

  redis-veggo:
    image: redis:7.2
    container_name: redis-veggo
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONT_PORT}"
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --save ""
      --appendonly no
      --maxclients 10000
      --timeout 0
      --tcp-keepalive 60
    networks:
      - network-veggo

  redpanda-veggo:
    image: redpandadata/redpanda:latest
    container_name: redpanda-veggo
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "${KAFKA_INTERNAL_PORT}:${KAFKA_INTERNAL_PORT}"
      - "${KAFKA_HOST_PORT}:${KAFKA_CONT_PORT}"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false

      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092

      - --advertise-kafka-addr=internal://redpanda-veggo:9092,external://localhost:19092
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    networks:
    - network-veggo

  redpanda-console-veggo:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console-veggo
    depends_on:
      redpanda-veggo:
        condition: service_healthy
    ports:
      - "${KAFKA_UI_HOST_PORT}:8080"
    environment:
      KAFKA_BROKERS: redpanda-veggo:9092
    networks:
      - network-veggo

  opensearch-veggo:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-veggo
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    ports:
      - "${OPENSEARCH_HOST_PORT}:9200"
      - "${OPENSEARCH_INTERNAL_PORT}:9600"
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g # Local Development
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - network-veggo

  opensearch-dashboard-veggo:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboard-veggo
    depends_on:
      opensearch-veggo:
        condition: service_healthy
    ports:
      - "${OPENSEARCH_DASHBOARD_PORT}:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-veggo:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    networks:
      - network-veggo

  api-gateway-veggo:
    build:
      context: ../services/api-gateway
      dockerfile: Dockerfile
    image: veggo/api-gateway:latest
    container_name: api-gateway-veggo
    depends_on:
      redis-veggo:
        condition: service_started
    ports:
      - "${API_GATEWAY_HOST_PORT}:${API_GATEWAY_CONT_PORT}"
    environment:
      APP_PORT: ${API_GATEWAY_CONT_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${API_GATEWAY}
      WEB_PREFORK: ${WEB_PREFORK}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: http://user-service-veggo:${USER_SERVICE_CONT_PORT}
      PRODUCT_SERVICE_URL: http://product-service-veggo:${PRODUCT_SERVICE_CONT_PORT}
      ORDER_SERVICE_URL:  http://order-service-veggo:${ORDER_SERVICE_CONT_PORT}
      PAYMENT_SERVICE_URL: http://payment-service-veggo:${PAYMENT_SERVICE_CONT_PORT}
      NOTIFICATION_SERVICE_URL: http://notification-service-veggo:${NOTIFICATION_SERVICE_CONT_PORT}
      RATE_LIMIT_REQUESTS_PER_SECOND: ${RATE_LIMIT_REQUESTS_PER_SECOND}
      RATE_LIMIT_BURST_SIZE: ${RATE_LIMIT_BURST_SIZE}
      REDIS_HOST: redis-veggo
      REDIS_PORT: ${REDIS_CONT_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      GATEWAY_SECRET_KEY: ${GATEWAY_SECRET_KEY}
    networks:
      - network-veggo

  user-service-veggo:
    build:
      context: ../services/user-service
      dockerfile: Dockerfile
    image: veggo/user-service:latest
    container_name: user-service-veggo
    depends_on:
      postgres-veggo:
        condition: service_healthy
      redpanda-veggo:
        condition: service_started
      minio-veggo:
        condition: service_started
      redis-veggo:
        condition: service_started
    environment:
      APP_PORT: ${USER_SERVICE_CONT_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${USER_SERVICE_NAME}
      WEB_PREFORK: ${WEB_PREFORK}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET_KEY: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      URL_FORGOT_PASSWORD: http://localhost:${API_GATEWAY_HOST_PORT}
      URL_FRONT_FE: "http://localhost:${API_GATEWAY_HOST_PORT}" # sementara
      DATABASE_HOST: postgres-veggo
      DATABASE_PORT: ${DATABASE_CONT_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${USER_SERVICE_DB}
      DATABASE_MAX_OPEN_CONNECTION: ${DATABASE_MAX_OPEN_CONNECTION}
      DATABASE_MAX_IDLE_CONNECTION: ${DATABASE_MAX_IDLE_CONNECTION}
      KAFKA_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET}
      KAFKA_BOOTSTRAP_SERVERS: redpanda-veggo:${KAFKA_INTERNAL_PORT}
      KAFKA_GROUP_ID: ${USER_SERVICE_KAFKA_GROUP_ID}
      KAFKA_PRODUCER_ENABLED: ${KAFKA_PRODUCER_ENABLED}
      TOPIC_NOTIF_EMAIL_VERIFICATION: ${TOPIC_NOTIF_EMAIL_VERIFICATION}
      TOPIC_NOTIF_EMAIL_FORGOT_PASSWORD: ${TOPIC_NOTIF_EMAIL_FORGOT_PASSWORD}
      TOPIC_NOTIF_EMAIL_CREATE_CUSTOMER: ${TOPIC_NOTIF_EMAIL_CREATE_CUSTOMER}
      TOPIC_NOTIF_EMAIL_UPDATE_CUSTOMER: ${TOPIC_NOTIF_EMAIL_UPDATE_CUSTOMER}
      TOPIC_PUSH_NOTIF: ${TOPIC_PUSH_NOTIF}
      MINIO_ENDPOINT: minio-veggo:${MINIO_CONT_PORT}
      MINIO_PUBLIC_URL: http://localhost:${MINIO_HOST_PORT} # pakai local
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${USER_SERVICE_MINIO_BUCKET}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      REDIS_HOST: redis-veggo
      REDIS_PORT: ${REDIS_CONT_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      GATEWAY_SECRET_KEY: ${GATEWAY_SECRET_KEY}
    networks:
      - network-veggo

  product-service-veggo:
    build:
      context: ../services/product-service
      dockerfile: Dockerfile
    image: veggo/product-service:latest
    container_name: product-service-veggo
    depends_on:
      postgres-veggo:
        condition: service_healthy
      redpanda-veggo:
        condition: service_started
      minio-veggo:
        condition: service_started
      redis-veggo:
        condition: service_started
      opensearch-veggo:
        condition: service_healthy
    environment:
      APP_PORT: ${PRODUCT_SERVICE_CONT_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${PRODUCT_SERVICE_NAME}
      WEB_PREFORK: ${WEB_PREFORK}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET_KEY: ${JWT_SECRET}
      GATEWAY_SECRET_KEY: ${GATEWAY_SECRET_KEY}
      REQUEST_API_GATEWAY: ${REQUEST_API_GATEWAY}
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
      DATABASE_HOST: postgres-veggo
      DATABASE_PORT: ${DATABASE_CONT_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${PRODUCT_SERVICE_DB}
      DATABASE_MAX_OPEN_CONNECTION: ${DATABASE_MAX_OPEN_CONNECTION}
      DATABASE_MAX_IDLE_CONNECTION: ${DATABASE_MAX_IDLE_CONNECTION}
      KAFKA_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET}
      KAFKA_BOOTSTRAP_SERVERS: redpanda-veggo:${KAFKA_INTERNAL_PORT}
      KAFKA_GROUP_ID: ${PRODUCT_SERVICE_KAFKA_GROUP_ID}
      KAFKA_PRODUCER_ENABLED: ${KAFKA_PRODUCER_ENABLED}
      TOPIC_PRODUCT_PUBLISH: ${TOPIC_PRODUCT_PUBLISH}
      TOPIC_PRODUCT_DELETE: ${TOPIC_PRODUCT_DELETE}
      MINIO_ENDPOINT: minio-veggo:${MINIO_CONT_PORT}
      MINIO_PUBLIC_URL: http://localhost:${MINIO_HOST_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${PRODUCT_SERVICE_MINIO_BUCKET}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      REDIS_HOST: redis-veggo
      REDIS_PORT: ${REDIS_CONT_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPENSEARCH_HOST: http://opensearch-veggo:9200
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
    networks:
      - network-veggo

  product-worker-veggo:
    image: veggo/product-service:latest
    container_name: product-worker-veggo
    command: ["./product-service", "worker"]
    depends_on:
      postgres-veggo:
        condition: service_healthy
      redpanda-veggo:
        condition: service_started
      minio-veggo:
        condition: service_started
      redis-veggo:
        condition: service_started
      opensearch-veggo:
        condition: service_healthy
    environment:
      APP_PORT: ${PRODUCT_SERVICE_CONT_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${PRODUCT_SERVICE_NAME}
      WEB_PREFORK: ${WEB_PREFORK}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET_KEY: ${JWT_SECRET}
      GATEWAY_SECRET_KEY: ${GATEWAY_SECRET_KEY}
      REQUEST_API_GATEWAY: ${REQUEST_API_GATEWAY}
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
      DATABASE_HOST: postgres-veggo
      DATABASE_PORT: ${DATABASE_CONT_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${PRODUCT_SERVICE_DB}
      DATABASE_MAX_OPEN_CONNECTION: ${DATABASE_MAX_OPEN_CONNECTION}
      DATABASE_MAX_IDLE_CONNECTION: ${DATABASE_MAX_IDLE_CONNECTION}
      KAFKA_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET}
      KAFKA_BOOTSTRAP_SERVERS: redpanda-veggo:${KAFKA_INTERNAL_PORT}
      KAFKA_GROUP_ID: ${PRODUCT_SERVICE_KAFKA_GROUP_ID}
      KAFKA_PRODUCER_ENABLED: ${KAFKA_PRODUCER_ENABLED}
      TOPIC_PRODUCT_PUBLISH: ${TOPIC_PRODUCT_PUBLISH}
      TOPIC_PRODUCT_DELETE: ${TOPIC_PRODUCT_DELETE}
      MINIO_ENDPOINT: minio-veggo:${MINIO_CONT_PORT}
      MINIO_PUBLIC_URL: http://localhost:${MINIO_HOST_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${PRODUCT_SERVICE_MINIO_BUCKET}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      REDIS_HOST: redis-veggo
      REDIS_PORT: ${REDIS_CONT_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPENSEARCH_HOST: http://opensearch-veggo:9200
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
    networks:
      - network-veggo

  payment-service-veggo:
    build:
      context: ../services/payment-service
      dockerfile: Dockerfile
    image: veggo/payment-service:latest
    container_name: payment-service-veggo
    depends_on:
      postgres-veggo:
        condition: service_healthy
      redpanda-veggo:
        condition: service_started
      redis-veggo:
        condition: service_started
    environment:
      APP_PORT: ${PAYMENT_SERVICE_CONT_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${PAYMENT_SERVICE_NAME}
      WEB_PREFORK: ${WEB_PREFORK}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET_KEY: ${JWT_SECRET}
      GATEWAY_SECRET_KEY: ${GATEWAY_SECRET_KEY}
      REQUEST_API_GATEWAY: ${REQUEST_API_GATEWAY}
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
      SERVER_TIMEOUT: ${SERVER_TIMEOUT}
      PRODUCT_SERVICE_URL: http://product-service-veggo:${PRODUCT_SERVICE_CONT_PORT}
      USER_SERVICE_URL: http://user-service-veggo:${USER_SERVICE_CONT_PORT}
      ORDER_SERVICE_URL: http://order-service-veggo:${ORDER_SERVICE_CONT_PORT}
      DATABASE_HOST: postgres-veggo
      DATABASE_PORT: ${DATABASE_CONT_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${PAYMENT_SERVICE_DB}
      DATABASE_MAX_OPEN_CONNECTION: ${DATABASE_MAX_OPEN_CONNECTION}
      DATABASE_MAX_IDLE_CONNECTION: ${DATABASE_MAX_IDLE_CONNECTION}
      KAFKA_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET}
      KAFKA_BOOTSTRAP_SERVERS: redpanda-veggo:${KAFKA_INTERNAL_PORT}
      KAFKA_GROUP_ID: ${PAYMENT_SERVICE_KAFKA_GROUP_ID}
      KAFKA_PRODUCER_ENABLED: ${KAFKA_PRODUCER_ENABLED}
      TOPIC_PAYMENT_SUCCESS: ${TOPIC_PAYMENT_SUCCESS}
      REDIS_HOST: redis-veggo
      REDIS_PORT: ${REDIS_CONT_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MIDTRANS_SERVER_KEY: ${MIDTRANS_SERVER_KEY}
      MIDTRANS_ENVIRONMENT: ${MIDTRANS_ENVIRONMENT}
    networks:
      - network-veggo

  order-service-veggo:
    build:
      context: ../services/order-service
      dockerfile: Dockerfile
    image: veggo/order-service:latest
    container_name: order-service-veggo
    depends_on:
      postgres-veggo:
        condition: service_healthy
      redpanda-veggo:
        condition: service_started
      redis-veggo:
        condition: service_started
      opensearch-veggo:
        condition: service_healthy
    environment:
      APP_PORT: ${ORDER_SERVICE_CONT_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${ORDER_SERVICE_NAME}
      WEB_PREFORK: ${WEB_PREFORK}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET_KEY: ${JWT_SECRET}
      GATEWAY_SECRET_KEY: ${GATEWAY_SECRET_KEY}
      REQUEST_API_GATEWAY: ${REQUEST_API_GATEWAY}
      INTERNAL_SECRET_KEY: ${INTERNAL_SECRET_KEY}
      SERVER_TIMEOUT: ${SERVER_TIMEOUT}
      PRODUCT_SERVICE_URL: http://product-service-veggo:${PRODUCT_SERVICE_CONT_PORT}
      USER_SERVICE_URL: http://user-service-veggo:${USER_SERVICE_CONT_PORT}
      DATABASE_HOST: postgres-veggo
      DATABASE_PORT: ${DATABASE_CONT_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${ORDER_SERVICE_DB}
      DATABASE_MAX_OPEN_CONNECTION: ${DATABASE_MAX_OPEN_CONNECTION}
      DATABASE_MAX_IDLE_CONNECTION: ${DATABASE_MAX_IDLE_CONNECTION}
      KAFKA_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET}
      KAFKA_BOOTSTRAP_SERVERS: redpanda-veggo:${KAFKA_INTERNAL_PORT}
      KAFKA_GROUP_ID: ${ORDER_SERVICE_KAFKA_GROUP_ID}
      KAFKA_PRODUCER_ENABLED: ${KAFKA_PRODUCER_ENABLED}
      TOPIC_PRODUCT_UPDATE_STOCK: ${TOPIC_PRODUCT_UPDATE_STOCK}
      TOPIC_ORDER_PUBLISH: ${TOPIC_ORDER_PUBLISH}
      TOPIC_EMAIL_UPDATE_STATUS: ${TOPIC_EMAIL_UPDATE_STATUS}
      TOPIC_DELETE_ORDER: ${TOPIC_DELETE_ORDER}
      TOPIC_PAYMENT_SUCCESS: ${TOPIC_PAYMENT_SUCCESS}
      TOPIC_UPDATE_STATUS_ORDER: ${TOPIC_UPDATE_STATUS_ORDER}
      TOPIC_PUSH_NOTIF_ORDER: ${TOPIC_PUSH_NOTIF_ORDER}
      REDIS_HOST: redis-veggo
      REDIS_PORT: ${REDIS_CONT_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      OPENSEARCH_HOST: http://opensearch-veggo:9200
      OPENSEARCH_USERNAME: ${OPENSEARCH_USERNAME}
      OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
    networks:
      - network-veggo

  notification-service-veggo:
    build:
      context: ../services/notification-service
      dockerfile: Dockerfile
    image: veggo/notification-service:latest
    container_name: notification-service-veggo
    depends_on:
      postgres-veggo:
        condition: service_healthy
      redpanda-veggo:
        condition: service_started
      redis-veggo:
        condition: service_started
    environment:
      APP_PORT: ${NOTIFICATION_SERVICE_CONT_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${NOTIFICATION_SERVICE_NAME}
      WEB_PREFORK: ${WEB_PREFORK}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET_KEY: ${JWT_SECRET}
      GATEWAY_SECRET_KEY: ${GATEWAY_SECRET_KEY}
      REQUEST_API_GATEWAY: ${REQUEST_API_GATEWAY}
      DATABASE_HOST: postgres-veggo
      DATABASE_PORT: ${DATABASE_CONT_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${NOTIFICATION_SERVICE_DB}
      DATABASE_MAX_OPEN_CONNECTION: ${DATABASE_MAX_OPEN_CONNECTION}
      DATABASE_MAX_IDLE_CONNECTION: ${DATABASE_MAX_IDLE_CONNECTION}
      KAFKA_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET}
      KAFKA_BOOTSTRAP_SERVERS: redpanda-veggo:${KAFKA_INTERNAL_PORT}
      KAFKA_GROUP_ID: ${NOTIFICATION_SERVICE_KAFKA_GROUP_ID}
      KAFKA_PRODUCER_ENABLED: ${KAFKA_PRODUCER_ENABLED}
      TOPIC_NOTIF_EMAIL_VERIFICATION: ${TOPIC_NOTIF_EMAIL_VERIFICATION}
      TOPIC_NOTIF_EMAIL_FORGOT_PASSWORD: ${TOPIC_NOTIF_EMAIL_FORGOT_PASSWORD}
      TOPIC_NOTIF_EMAIL_CREATE_CUSTOMER: ${TOPIC_NOTIF_EMAIL_CREATE_CUSTOMER}
      TOPIC_EMAIL_UPDATE_STATUS: ${TOPIC_EMAIL_UPDATE_STATUS}
      TOPIC_PUSH_NOTIF: ${TOPIC_PUSH_NOTIF}
      REDIS_HOST: redis-veggo
      REDIS_PORT: ${REDIS_CONT_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SENDING: ${EMAIL_SENDING}
      EMAIL_IS_TLS: ${EMAIL_IS_TLS}
    networks:
      - network-veggo

  notification-worker-veggo:
    image: veggo/notification-service:latest
    container_name: notification-worker-veggo
    command: ["./notification-service", "worker"]
    depends_on:
      postgres-veggo:
        condition: service_healthy
      redpanda-veggo:
        condition: service_started
      redis-veggo:
        condition: service_started
    environment:
      APP_PORT: ${NOTIFICATION_SERVICE_CONT_PORT}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${NOTIFICATION_SERVICE_NAME}
      WEB_PREFORK: ${WEB_PREFORK}
      LOG_LEVEL: ${LOG_LEVEL}
      JWT_SECRET_KEY: ${JWT_SECRET}
      GATEWAY_SECRET_KEY: ${GATEWAY_SECRET_KEY}
      REQUEST_API_GATEWAY: ${REQUEST_API_GATEWAY}
      DATABASE_HOST: postgres-veggo
      DATABASE_PORT: ${DATABASE_CONT_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${NOTIFICATION_SERVICE_DB}
      DATABASE_MAX_OPEN_CONNECTION: ${DATABASE_MAX_OPEN_CONNECTION}
      DATABASE_MAX_IDLE_CONNECTION: ${DATABASE_MAX_IDLE_CONNECTION}
      KAFKA_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET}
      KAFKA_BOOTSTRAP_SERVERS: redpanda-veggo:${KAFKA_INTERNAL_PORT}
      KAFKA_GROUP_ID: ${NOTIFICATION_SERVICE_KAFKA_GROUP_ID}
      KAFKA_PRODUCER_ENABLED: ${KAFKA_PRODUCER_ENABLED}
      TOPIC_NOTIF_EMAIL_VERIFICATION: ${TOPIC_NOTIF_EMAIL_VERIFICATION}
      TOPIC_NOTIF_EMAIL_FORGOT_PASSWORD: ${TOPIC_NOTIF_EMAIL_FORGOT_PASSWORD}
      TOPIC_NOTIF_EMAIL_CREATE_CUSTOMER: ${TOPIC_NOTIF_EMAIL_CREATE_CUSTOMER}
      TOPIC_EMAIL_UPDATE_STATUS: ${TOPIC_EMAIL_UPDATE_STATUS}
      TOPIC_PUSH_NOTIF: ${TOPIC_PUSH_NOTIF}
      REDIS_HOST: redis-veggo
      REDIS_PORT: ${REDIS_CONT_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SENDING: ${EMAIL_SENDING}
      EMAIL_IS_TLS: ${EMAIL_IS_TLS}
    networks:
      - network-veggo

  fe-veggo:
    build:
      context: ../frontend/veggo-fe
      dockerfile: Dockerfile
    image: veggo/veggo-fe:latest
    container_name: fe-veggo
    depends_on:
      api-gateway-veggo:
        condition: service_started
    ports:
      - "${HOST_FE_PORT}:${CONT_FE_PORT}"
    environment:
      VEGGO_API_BASE_URL: http://api-gateway-veggo:${API_GATEWAY_CONT_PORT}/api/v1
      MIDTRANS_CLIENT_KEY: ${MIDTRANS_CLIENT_KEY}
    networks:
      - network-veggo


volumes:
  postgresql_data:
  minio_data:
  opensearch_data:
  redpanda_data:

networks:
  network-veggo:
    driver: bridge
